### ISSUE TITLE
Null pointer in demo popup menu

### ISSUE THREAD

**Issue by YoeriNijs** [fjalvingh/domui#22]
When I was clicking around in the popup menu component in the demo application, the first link for the simple popup menu was causing a null pointer. According to the stacktrace line 94 is responsible for this: https://github.com/fjalvingh/domui/blob/f1713b72622ab2057ddb6c8098b5782d078959d1/to.etc.domui/src/main/java/to/etc/domui/component/menu/SimplePopupMenu.java#L94

**Comment by fjalvingh** [comment]
Bad bug in old code. I fixed the issue, and put the component on the list for some TLC. Thanks for reporting!
