### ISSUE TITLE
Sass compiler is causing problems

### ISSUE THREAD

**Issue by YoeriNijs** [fjalvingh/domui#7]
After cloning DomUI and importing it in IntelliJ (with Maven reimports enabled by default), I tried to run it. However, the Vaadin Sass compiler is causing a lot of headache, frankly. For instance, the compiler throws an error because it cannot find the parser import (see log below). Alt+enter is providing various import suggestions, but not the one from Vaadin itself. Therefore, I tried various other things in order to get it work. For example, reimporting the Maven sources, checking the pom files, rebuilding the whole project et cetera. Nothing seems to work, unfortunately. Maybe I am doing just something wrong?

![2b8g8ux](https://user-images.githubusercontent.com/4572798/28996731-23bca5d4-7a06-11e7-8db4-a056649c9a72.png)

**Comment by fjalvingh** [comment]
Welcome to the wonderful world of Maven.
You need to run a Maven compile on the command line or in the Maven tab of
intellij..
