### ISSUE TITLE
Button Hide in the SearchPanel is working incorrect 

### ISSUE THREAD

**Issue by molshoop** [fjalvingh/domui#72]
If you click on the Hide button in de SearchPanel, the search criteria are not hidden instead the buttons Search and Add are shown on the next line
![screenshot from 2018-06-05 23-51-46](https://user-images.githubusercontent.com/8713469/41004810-75f4c91c-691b-11e8-88aa-5162aa6c0124.png)

**Comment by fjalvingh** [comment]
Fixed.
